#!/bin/bash

if [ $# -eq 0 -a -t 0 ]; then
    echo "Usage: newline [options] [<files>]" >&2
    exit 2
elif [ "$1" == "-i" -o "$1" == "--info" ]; then
    newline=0
    if [ -t 0 ]; then
        params=("${@}")
    else
        params=("${@}" $(cat /dev/stdin))
    fi
    for i in "${!params[@]}"; do
        if [[ "${params[$i]}" != "-"* ]]; then
            if [ -d "${params[$i]}" ]; then
                change_params=$(echo "${params[$i]}" | sed 's/\/$//')
                echo "Please change ${params[$i]} to $change_params/*" >&2
                echo "or use this command: \`find $change_params -type f | newline --info\`" >&2
                continue
            elif [ -f "${params[$i]}" ]; then
                if [ $newline -gt 0 ]; then
                    echo ""
                fi
                binary_check=$(file -bL --mime "${params[$i]}" | grep "binary")
                if [ $? -eq 0 ]; then
                    echo "skipping ${params[$i]} file. reason: binary file." >&2
                    continue
                fi
                file "${params[$i]}" 2> /dev/null
                which xxd &> /dev/null
                if [ $? -eq 0 ]; then
                    xxd -l 32 "${params[$i]}"
                else
                    echo "Please install vim to use xxd command." >&2
                fi
                newline=$(expr $newline + 1)
            else
                echo "unable to locate ${params[$i]} file. no such file or directory" >&2
            fi
        fi
    done
    exit 0
elif [ "$1" == "-h" -o "$1" == "--help" ]; then
    echo 'Determine type of files or converting EOL between LF and CRLF.'
    echo -e '\nUsage: newline [options] [<files>]'
    echo -e '\nOptions: '
    echo -e ' -h, --help\t\tdisplay this help and exit'
    echo -e ' -i, --info FILEs\tdisplay provide file type and properties'
    echo -e '     --type=EOL\t\tlimiting `EOL` type when using converter'
    echo -e '\t\t\t`EOL` only accepted `CRLF` and `LF` (NAK `\\r\\n` or `\\n`)'
    echo -e ' --bom\t\t\tensure file has UTF-8 BOM'
    echo -e ' --nobom\t\tremove UTF-8 BOM from file'
    echo -e ' FILEs\t\t\tconverting files EOL in provided params'
    echo -e '\nEXIT STATUS'
    echo -e ' 0\t operation Successful'
    echo -e ' 1\t operation Failed'
    echo -e ' 2\t unknown command or parameter type'
    echo -e '\nEXAMPLES'
    echo 'Print example.txt file EOL type and properties'
    echo '% newline -i example.txt'
    echo ''
    echo 'Convert example.txt file other support EOL type'
    echo '% newline example.txt'
    echo ''
    echo 'Convert example.txt file EOL type to CRLF'
    echo '% newline --type=CRLF example.txt'
    echo ''
    echo "Convert files EOL type to LF recursively from specified directory"
    echo "% find /path/to/directory -type f | newline --type=LF"
    echo "% find /path/to/directory -type f -exec newline --type=LF {} \\;"
    exit 0
fi

constantEOF=""
constantBOM=""
if [ -t 0 ]; then
    params=("${@}")
else
    params=("${@}" $(cat /dev/stdin))
fi

for i in "${!params[@]}"; do
    if [[ "${params[$i]}" == "-"* ]]; then
        if [ "${params[$i]}" == "--type=LF" -o "${params[$i]}" == "--type=lf" ]; then
            constantEOF="LF"
        elif [ "${params[$i]}" == "--type=CRLF" -o "${params[$i]}" == "--type=crlf" ]; then
            constantEOF="CRLF"
        elif [ "${params[$i]}" == "--bom" ]; then
            constantBOM="ADD"
        elif [ "${params[$i]}" == "--nobom" ]; then
            constantBOM="REMOVE"
        else
            echo "error: unknown ${params[$i]} parameter. Aborting." >&2
            exit 1
        fi
        continue
    fi

    if [ -d "${params[$i]}" ]; then
        change_params=$(echo "${params[$i]}" | sed 's/\/$//')
        echo "Please change ${params[$i]} to $change_params/*" >&2
        if [ x$constantEOF == x ]; then
            echo "or use this command: \`find $change_params -type f | newline\`" >&2
        else
            echo "or use this command: \`find $change_params -type f | newline --type=$constantEOF\`" >&2
        fi
        continue
    elif ! [ -r "${params[$i]}" ]; then
        echo "unable to locate ${params[$i]} file. no such file or directory" >&2
        continue
    elif ! [ -w "${params[$i]}" ]; then
        echo "unable to access ${params[$i]} file. permission denied." >&2
        continue
    fi

    binary_check=$(file -bL --mime "${params[$i]}" | grep "binary")
    if [ $? -eq 0 ]; then
        echo "skipping ${params[$i]} file. reason: binary file." >&2
        continue
    fi

    file_info=$(file -b "${params[$i]}")
    is_crlf=$(echo "$file_info" | grep "CRLF")

    if echo "$file_info" | grep -q "CR" && ! echo "$file_info" | grep -q "LF"; then
        echo "unable to convert ${params[$i]}. reason: unsupported EOL CR(Macintosh) type." >&2
        continue
    fi

    if [ "$constantEOF" == "LF" ]; then
        if [ -n "$is_crlf" ]; then
            sed -i 's/\r$//' "${params[$i]}" && echo "${params[$i]}: converted CRLF to LF."
        fi
    elif [ "$constantEOF" == "CRLF" ]; then
        if [ -z "$is_crlf" ]; then
            sed -i 's/$/\r/' "${params[$i]}" && echo "${params[$i]}: converted LF to CRLF."
        fi
    fi

    current_bom=$(head -c 3 "${params[$i]}")
    target_bom=$'\xef\xbb\xbf'

    if [ "$constantBOM" == "ADD" ]; then
        if [ "$current_bom" != "$target_bom" ]; then
            printf '%s' "$target_bom" > "${params[$i]}.tmp"
            cat "${params[$i]}" >> "${params[$i]}.tmp"
            mv "${params[$i]}.tmp" "${params[$i]}"
            echo "${params[$i]}: Added UTF-8 BOM."
        fi
    elif [ "$constantBOM" == "REMOVE" ]; then
        if [ "$current_bom" == "$target_bom" ]; then
            tail -c +4 "${params[$i]}" > "${params[$i]}.tmp"
            mv "${params[$i]}.tmp" "${params[$i]}"
            echo "${params[$i]}: Removed UTF-8 BOM."
        fi
    fi
done

