#!/bin/bash

exitCode=0
prevDir=$(pwd)

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Unknown OS: $(uname -s). Aborting."
    exit 1
fi

function gitUpdate() {
    repoName=("Release/ShellScript" "Release/PasswordsGenerator" "Release/Dotfiles")
    if [ -r "/mnt/c/Windows/System32/cmd.exe" ]; then
        repoName+=("Release/Games/World of Warcraft/macros")
        repoName+=("Release/Games/World of Warcraft/WeakAuras")
    fi

    for target in "${repoName[@]}"; do
        if [ -d "$HOME/Documents/$target" ]; then
            echo -e "\n\033[37mupdater: Updating repo ~/Documents/$target...\033[m"
            cd "$HOME/Documents/$target" || return
            if ! git pull --rebase --stat origin "$(git branch --show-current)"; then
                git status
            fi

            if ! cd - &>/dev/null; then
                echo -e "\033[31mupdater: exception occurred: return original directory function corrupted: $prevDir currently not accessible. \033[m"
                cd ~ || return
                echo "updater: autofix: Fix broken original directory to $HOME."
            fi
        fi
    done
}

gitUpdate
if [ -r "/mnt/c/Windows/System32/cmd.exe" ]; then
    ~/Documents/Release/ShellScript/Specific/Windows/WSL/extension
else
    ~/Documents/Release/ShellScript/Specific/Linux/General/extension
fi

