#!/bin/bash

exitCode=0
prevDir=$(pwd)

function gitUpdate() {
    repoName=("Release/ShellScript" "Release/PasswordsGenerator" "Release/Dotfiles")
    if [ "$(uname -s)" == "Darwin" ]; then
        repoName+=("Release/aptall")
    elif [ "$(uname -s)" == "Linux" ]; then
        repoName+=("Release/brewall" "Release/ArtDisplay")

        if [ -r "/mnt/c/Windows/System32/cmd.exe" ]; then
            repoName+=("Release/Games/Diablo II Resurrected/seonhee")

            repoName+=("Release/Games/World of Warcraft/macros")
            repoName+=("Release/Games/World of Warcraft/WeakAuras")

            repoName+=("Release/Games/World of Warcraft/AddOns/TalentSequence")
            repoName+=("Release/Games/World of Warcraft/AddOns/WeaponSwingTimer")
            repoName+=("Release/Games/World of Warcraft/AddOns/FlightTimerClassic")
            repoName+=("Release/Games/World of Warcraft/AddOns/WhereToGatherClassic")
            repoName+=("Release/Games/World of Warcraft/AddOns/AddOnsUpdater")
        fi
    fi

    for target in "${repoName[@]}"; do
        if [ -d "$HOME/Documents/$target" ]; then
            echo -e "\n\033[37mupdater: Updating repo ~/Documents/$target...\033[m"
            cd "$HOME/Documents/$target" || return
            if ! git pull --rebase --stat origin "$(git branch --show-current)"; then
                git status
            fi

            if ! cd - &>/dev/null; then
                echo -e "\033[31mupdater: exception occurred: return original directory function corrupted: $prevDir currently not accessible. \033[m"
                cd ~ || return
                echo "updater: autofix: Fix broken original directory to $HOME."
            fi
        fi
    done
}

if [ "$SKIP_PACKAGE_UPDATER" == "true" ]; then
    gitUpdate
    if [ "$(uname -s)" == "Darwin" ]; then
        if [ -x ~/Documents/Release/ShellScript/Operating\ System/macOS/Private/extension ]; then
            ~/Documents/Release/ShellScript/Operating\ System/macOS/Private/extension
        fi
    elif [ "$(uname -s)" == "Linux" ]; then
        if [ -x ~/Documents/Release/ShellScript/Operating\ System/Linux/General/extension ]; then
            ~/Documents/Release/ShellScript/Operating\ System/Linux/General/extension
        elif [ -x ~/Documents/Release/ShellScript/Operating\ System/Linux/RaspberryPi/extension ]; then
            ~/Documents/Release/ShellScript/Operating\ System/Linux/RaspberryPi/extension
        fi
    fi
    exit $exitCode
fi

if [ "$(uname -s)" == "Darwin" ]; then
    if [ -x ~/Documents/Release/brewall/brewall.sh ]; then
        ~/Documents/Release/brewall/brewall.sh "$@"
        if [ $# == 0 ]; then
            gitUpdate
        fi
        exitCode=$?
    else
        gitUpdate
    fi
elif [ "$(uname -s)" == "Linux" ]; then
    if [ -x ~/Documents/Release/aptall/aptall.sh ]; then
        ~/Documents/Release/aptall/aptall.sh "$@"
        aptall_exit=$?
        if [ $aptall_exit -ne 127 ] && [ $# == 0 ]; then
            gitUpdate
        fi
        exitCode=$aptall_exit
    else
        gitUpdate
    fi
else
    echo "Unknown OS: $(uname -s). Aborting."
    exitCode=1
fi

exit $exitCode
