#!/bin/bash

if which nvim &> /dev/null; then
    if ! nvim --version > /dev/null; then
        echo 'neovim package was corrupted.'
        echo 'Please re-install neovim in below link.'
        echo -e "\thttps://github.com/neovim/neovim/releases/latest"
    else
        local=$(nvim --version | grep NVIM | cut -d- -f1 | sed 's/NVIM v//')
        release=$(curl -fsSL https://github.com/neovim/neovim/releases/latest | grep '<title>' | awk '{ print $3  }')
        if dpkg --compare-versions "$local" lt "$release"; then
            if [ -d ~/snap/neovim ]; then
                cd ~/snap/neovim || exit
                git pull --rebase origin "$(git branch --show-current)"
                make CMAKE_BUILD_TYPE=Release
                sudo make install
            else
                echo 'Please download neovim in below link.'
                echo -e "\thttps://github.com/neovim/neovim/releases/latest"
            fi
        else
            echo "Neovim is up to date ($local)."
        fi
    fi
fi

if which wsl.exe &>/dev/null; then
    wsl.exe --status
    wsl.exe --version
    echo 'Please enter `wsl.exe --update` command if you wanna check WSL updates.'
fi

if which winget.exe &>/dev/null; then
#   cmd.exe "/c" "winget.exe upgrade --all"
    cmd.exe "/c" "winget.exe upgrade"
    echo -e "\e[m"
fi

if which juliaup &> /dev/null; then
    juliaup update
fi

if which docker &> /dev/null; then
    docker image prune -f
    docker volume prune -f
fi

if which zsh &>/dev/null; then
    if /bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"; then
        /bin/zsh -c "source ~/.zshrc; omz update" &
        targetPID=$!
        for (( i=0 ; i<=10 ; i++ )); do
            if ! ps | grep $targetPID &> /dev/null; then
                break
            fi
            sleep 1
        done
        if ps | grep $targetPID &> /dev/null; then
            kill $targetPID &> /dev/null
        fi
    fi
fi

if which flatpak &> /dev/null; then
    flatpak update
    flatpak uninstall --unused
fi

if which pip &> /dev/null; then
    if ! which deactivate &> /dev/null; then
        echo 'Please use pip venv packages instead of global system pip'
    fi
fi

find ~/.venv -maxdepth 1 -type d | while read venv; do
    if [ -x "$venv/bin/pip" ]; then
        echo -e "\n\033[37mupdater: Updating pip packages in: $venv...\033[m"

        "$venv/bin/python" -m venv --upgrade "$venv"
        "$venv/bin/python" -m pip install -U pip
        "$venv/bin/python" -m pip install -U "$(basename "$venv")"
    fi
done

