#!/bin/bash

which nvim &> /dev/null
if [ $? -eq 0 ]; then
    nvim --version > /dev/null
    if [ $? -ne 0 ]; then
        echo 'neovim package was corrupted.'
        echo 'Please re-install neovim in below link.'
        echo -e "\thttps://github.com/neovim/neovim/releases/latest"
    else
        local=$(nvim --version | grep NVIM | awk '{ print $2 }')
        release=$(curl -fsSL https://github.com/neovim/neovim/releases/latest | grep '<title>' | awk '{ print $3 }')
        if [ "$local" != "$release" ]; then
            echo 'Please download neovim in below link.'
            echo -e "\thttps://github.com/neovim/neovim/releases/latest"
        else
            echo "Neovim is up to date ($local)."
        fi
    fi
fi

which wsl.exe &>/dev/null
if [ $? == 0 ]; then
    wsl.exe --status
    wsl.exe --version
    echo 'Please enter `wsl.exe --update` command if you wanna check WSL updates.'
fi

which winget.exe &>/dev/null
if [ $? == 0 ]; then
  #     cmd.exe "/c" "winget.exe upgrade --all"
    cmd.exe "/c" "winget.exe upgrade"
    echo -e "\e[m"
fi

if [ -x ~/.local/bin/gitVI_update ]; then
    ~/.local/bin/gitVI_update
fi

which juliaup &> /dev/null
if [ $? -eq 0 ]; then
    juliaup update
fi

which docker &> /dev/null
if [ $? -eq 0 ]; then
    docker image prune -f
    docker volume prune -f
fi

which zsh &>/dev/null
if [ $? == 0 ]; then
    /bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"
    if [ $? == 0 ]; then
        /bin/zsh -c "source ~/.zshrc; omz update" &
        targetPID=$!
        for (( i=0 ; i<=10 ; i++ )); do
            ps | grep $targetPID &> /dev/null
            if [ $? -ne 0 ]; then
                break
            fi
            sleep 1
        done
        ps | grep $targetPID &> /dev/null
        if [ $? -eq 0 ]; then
            kill $targetPID &> /dev/null
        fi
    fi
fi

which flatpak &> /dev/null
if [ $? -eq 0 ]; then
    flatpak update
    flatpak uninstall --unused
fi

which pip &> /dev/null
if [ $? -eq 0 ]; then
    echo 'Please use pip venv packages instead of global system pip'
fi

find ~/.venv -maxdepth 1 -type d | while read venv; do
    if [ -x "$venv/bin/pip" ]; then
        echo "Updating manually installed packages in: $venv"

        "$venv/bin/python" -m pip install -U pip
        "$venv/bin/pip" list --not-required --format=freeze \
          | grep -v 'pip==' \
          | cut -d= -f1 \
          | xargs -I {} "$venv/bin/pip" install -U {}
    fi
done

