#!/bin/bash

launched=0
spoofdpi_pid=0

ps -ef | grep -v grep | grep spoofdpi &> /dev/null
if [ $? -ne 0 ]; then
    spoofdpi --port=12345 &
    spoofdpi_pid=$!
    sleep 5
    launched=1
fi

flatpak run com.google.Chrome --incognito --proxy-server=127.0.0.1:12345 https://google.com &
target_app_pid=$!

if [ $launched -eq 1 ]; then
    while :; do
        ps -ef | grep -v grep | grep -v $(basename $0) | grep $target_app_pid &> /dev/null
        if [ $? -ne 0 ]; then
            kill $spoofdpi_pid
            break
        fi
        sleep 1
    done
fi
