#!/bin/bash

launched=0
spoofdpi_pid=0
chrome_flags=

if [ -r "$HOME/.config/chrome-flags.conf" ]; then
    chrome_flags=$(grep -v '^\s*#' "$HOME/.config/chrome-flags.conf" | xargs)
fi

if ! pgrep -f spoofdpi &> /dev/null; then
    spoofdpi --listen-addr=127.0.0.1:12345 &
    spoofdpi_pid=$!
    sleep 5
    launched=1
fi

flatpak run com.google.Chrome --incognito --proxy-server=127.0.0.1:12345 https://google.com "$chrome_flags" &
target_app_pid=$!

if [ $launched -eq 1 ]; then
    while :; do
        if ! kill -0 "$target_app_pid" &> /dev/null; then
            kill $spoofdpi_pid
            break
        fi
        sleep 1
    done
fi
