#!/bin/bash

which nvim &> /dev/null
if [ $? -eq 0 ]; then
    nvim --version > /dev/null
    if [ $? -ne 0 ]; then
        echo 'neovim package was corrupted.'
        echo 'Please re-install neovim in below link.'
        echo -e "\thttps://github.com/neovim/neovim/releases/latest"
    else
        local=$(nvim --version | grep NVIM | awk '{ print $2 }' | awk -F '-' '{ print $1 }')
        release=$(curl -fsSL https://github.com/neovim/neovim/releases/latest | grep 'css-truncate css-truncate-target' | awk -F '/' '{ print $5 }' | cut -d\" -f1)
        target=$(vercmp $local $release)
        if [ $target -lt 0 ]; then
            if [ -d ~/snap/neovim ]; then
                cd ~/snap/neovim
                git pull --rebase origin $(git branch --show-current)
                make CMAKE_BUILD_TYPE=Release
                sudo make install
            else
                echo 'Please download neovim in below link.'
                echo -e "\thttps://github.com/neovim/neovim/releases/latest"
            fi
        else
            echo "Neovim is up to date ($local)."
        fi
    fi
fi

which juliaup &> /dev/null
if [ $? -eq 0 ]; then
    juliaup update
fi

which zsh &>/dev/null
if [ $? == 0 ]; then
    /bin/zsh -c "source ~/.zshrc; which omz > /dev/null 2>&1"
    if [ $? == 0 ]; then
        /bin/zsh -c "source ~/.zshrc; omz update" &
        targetPID=$!
        for (( i=0 ; i<=10 ; i++ )); do
            ps | grep $targetPID &> /dev/null
            if [ $? -ne 0 ]; then
                break
            fi
            sleep 1
        done
        ps | grep $targetPID &> /dev/null
        if [ $? -eq 0 ]; then
            kill $targetPID &> /dev/null
        fi
    fi
fi

which flatpak &> /dev/null
if [ $? -eq 0 ]; then
    flatpak update -y
    flatpak uninstall --unused
fi

which docker &> /dev/null
if [ $? -eq 0 ]; then
    docker image prune -f
    docker volume prune -f
fi

if [ -x /usr/bin/vmplayer ]; then
    vm_count=$(ls /lib/modules/$(uname -r)/misc 2> /dev/null | grep -c 'vm')
    if [ $vm_count -ne 2 ]; then
        echo 'Installing VMware modules: vmnet, vmmon'
        sudo vmware-modconfig --console --install-all
    else
        echo 'Requirement already satisfied: vmware-modconfig'
    fi
fi

# which pacman &> /dev/null
# if [ $? -eq 0 ]; then
#     ping -c 1 -W 1 -q "archlinux.org" &> /dev/null
#     if [ $? -eq 0 ]; then
#         curl -s 'https://archlinux.org/mirrorlist/?country=KR&country=JP&protocol=https&use_mirror_status=on' | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - | sudo tee /etc/pacman.d/mirrorlist
#     else
#         echo 'error: unable to connect `archlinux.org`. internal error occurred'
#     fi
# fi

# which eos-rankmirrors &> /dev/null
# if [ $? -eq 0 ]; then
#     sudo eos-rankmirrors
# fi

if [ $(systemctl is-enabled --user chrome-mimetype-remove) ]; then
    systemctl start --user chrome-mimetype-remove
fi

which pip &> /dev/null
if [ $? -eq 0 ]; then
    which deactivate &> /dev/null
    if [ $? -ne 0 ]; then
        echo 'Please use pip venv packages instead of global system pip'
    fi
fi

find ~/.venv -maxdepth 1 -type d | while read venv; do
    if [ -x "$venv/bin/pip" ]; then
        echo -e "\n\033[37mupdater: Updating pip packages in: $venv...\033[m"

        "$venv/bin/python" -m pip install -U pip
        "$venv/bin/pip" list --not-required --format=freeze \
          | grep -v 'pip==' \
          | cut -d= -f1 \
          | xargs -I {} "$venv/bin/pip" install -U {}
    fi
done

